services:
  - type: web
    name: backend-tareasync
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5001
      - key: MONGODB_URI
        value: mongodb+srv://admin:Tickets2026@tickets-cluster.5mikqmi.mongodb.net/tickets?retryWrites=true&w=majority&appName=tickets-cluster
      - key: JWT_SECRET
        generateValue: true
      - key: FRONTEND_URL
        value: https://tareasync.vercel.app
      - key: APP_URL
        value: https://tareasync.vercel.app
      - key: EMAIL_FROM
        value: envios@portfolioinvestment.com.ar
      - key: EMAIL_PASS
        value: lttjqnpackeiegekl
      - key: EMAIL_HOST
        value: smtp.gmail.com
      - key: EMAIL_PORT
        value: 587
      - key: CLOUDINARY_CLOUD_NAME
        value: dfuybsomz
      - key: CLOUDINARY_API_KEY
        value: 99688937873469
      - key: CLOUDINARY_API_SECRET
        value: WTxpehIVfMk-VDN6pw3dzQwyMIE
