// Componente de iconos simplificado (sin dependencias externas)
// Usa emojis profesionales y SVG inline para los iconos más comunes

export const Icon = ({ name, size = 20, color = 'currentColor', className = '' }) => {
  const icons = {
    // Acciones
    'BellOff': '🔕',
    'BellRing': '🔔',
    'CheckCircle': '✅',
    'AlertCircle': '⚠️',
    'X': '✖',
    'ChevronDown': '▼',
    'ChevronUp': '▲',
    'ChevronRight': '▶',
    'ChevronLeft': '◀',
    'Plus': '➕',
    'Edit': '✏️',
    'Trash': '🗑️',
    'Save': '💾',
    'Send': '📤',
    'Upload': '📤',
    'Download': '📥',
    'Search': '🔍',
    'Filter': '🔽',
    'Refresh': '🔄',
    'Loader': '⏳',
    'LoaderCircle': '⏳',
    'Calendar': '📅',
    'Clock': '⏰',
    'User': '👤',
    'Users': '👥',
    'Mail': '📧',
    'MessageSquare': '💬',
    'Image': '🖼️',
    'File': '📄',
    'Folder': '📁',
    'Home': '🏠',
    'Settings': '⚙️',
    'HelpCircle': '❓',
    'LogOut': '🚪',
    'Menu': '☰',
    'Sun': '☀️',
    'Moon': '🌙',
    'Eye': '👁️',
    'EyeOff': '🙈',
    'Lock': '🔒',
    'Unlock': '🔓',
    'Flag': '🚩',
    'Star': '⭐',
    'Heart': '❤️',
    'ThumbsUp': '👍',
    'ThumbsDown': '👎',
    'Share': '📤',
    'Link': '🔗',
    'ExternalLink': '🔗',
    'Info': 'ℹ️',
    'Warning': '⚠️',
    'Check': '✓',
    'XCircle': '❌',
    'CheckCircle2': '✅',
    'AlertTriangle': '⚠️',
    'Archive': '📦',
    'Inbox': '📥',
    'Send': '📤',
    'DownloadCloud': '☁️📥',
    'UploadCloud': '☁️📤',
    'Printer': '🖨️',
    'Copy': '📋',
    'MoreVertical': '⋮',
    'MoreHorizontal': '⋯',
    'GripVertical': '⋮',
    'GripHorizontal': '⋯',
    'Move': '⤴️',
    'Paperclip': '📎',
    'Tag': '🏷️',
    'Tags': '🏷️',
    'Hash': '#',
    'Activity': '📊',
    'BarChart': '📊',
    'LineChart': '📈',
    'PieChart': '🥧',
    'AreaChart': '📉',
    'LayoutList': '📋',
    'LayoutGrid': '🔲',
    'KanbanSquare': '🎯',
    'Ticket': '🎫',
    'TicketCheck': '✅🎫',
    'TicketX': '❌🎫',
    'PlayCircle': '▶️',
    'PauseCircle': '⏸️',
    'RotateCcw': '🔄',
    'Circle': '○',
    'TrendingUp': '📈',
    'TrendingDown': '📉',
    'Zap': '⚡',
    'Timer': '⏱️',
    'Hourglass': '⌛',
    'CalendarDays': '📅',
    'CalendarClock': '📅⏰',
    'CalendarRange': '📅📅',
    'CalendarPlus': '📅➕',
    'CalendarCheck': '📅✅',
    'CalendarX': '📅❌',
    'UserPlus': '👤➕',
    'UserMinus': '👤➖',
    'UserCheck': '👤✅',
    'UserX': '👤❌',
    'Phone': '📞',
    'Video': '🎥',
    'AtSign': '@',
    'FileImage': '🖼️📄',
    'FileText': '📄',
    'FolderOpen': '📂',
    'FolderArchive': '📦📁',
    'Shield': '🛡️',
    'ShieldCheck': '✅🛡️',
    'ShieldAlert': '⚠️🛡️',
    'Key': '🔑',
    'Fingerprint': '👆',
    'Cpu': '💻',
    'Server': '🖥️',
    'Database': '🗄️',
    'Wifi': '📶',
    'WifiOff': '📶❌',
    'Smile': '😊',
    'Frown': '😞',
    'Meh': '😐',
    'Github': '🐙',
    'Linkedin': '🔗',
    'Twitter': '🐦',
    'Globe': '🌐',
    'DollarSign': '💰',
    'Percent': '%'
  };

  const iconChar = icons[name];
  
  if (!iconChar) {
    console.warn(`Icono "${name}" no encontrado`);
    return <span className={`icon-placeholder ${className}`} style={{ width: size, height: size }} />;
  }

  return (
    <span 
      className={`icon-emoji ${className}`} 
      style={{ 
        fontSize: size, 
        color: color,
        display: 'inline-flex',
        alignItems: 'center',
        justifyContent: 'center',
        lineHeight: 1
      }}
    >
      {iconChar}
    </span>
  );
};

export default Icon;